### ISSUE TITLE
Using "official" kafka image

### ISSUE THREAD

**Issue by kornicameister** [monasca/monasca-docker#131]
Hi,

I've been wondering why exactly a custom kafka image was developed ? Instead of using existing image ?
For example [ches/kafka](https://hub.docker.com/r/ches/kafka/tags/) which has tags for also the kafka version it is used here.

**Comment by kornicameister** [comment]
@timothyb89  ?

**Comment by kornicameister** [comment]
See #132

**Comment by timothyb89** [comment]
I left some comments in #132, the short version is:
 * our image is much smaller (72%!)
 * we avoid licensing issues with Oracle java (via alpine + OpenJDK)
 * we get updates to Java/OpenJDK via alpine
 * we already have (or can easily add) the configuration features from ches/kafka (config story is much better with jinja2)
