### ISSUE TITLE
An approach to kafka-init

### ISSUE THREAD

**Issue by kornicameister** [monasca/monasca-docker#134]
Hi wanted to discuss some of the options about **kafka-init** image we've mentioned a while ago.

Basically, since like ever, the approach I've been taking (which also holds for this repository) to create, or rather manipulate, topics in kafka was to used ```kafka_topics.sh``` shipped together with kafka.
However that means that I'd actually need to install kafka to do this in easiest possible way (might be even to extend an existing image). 

Are you aware of any other tools there might be ?
I will try do some digging but approach lied out above seems, at least now, the only approach possible.

**Comment by timothyb89** [comment]
Huh, I thought our `create_topics.py` created topics through pykafka, but it seems to be just calling out to that same `kafka_topics.sh` script. Guess my memory isn't so good :smile: 

I think you're right though, shelling out to `kafka_topics.sh` seems to be the only real way to do it. Our best bet would be to extend our kafka image with the init tools to at least give Docker/k8s a chance to reuse the downloaded data.

**Comment by kornicameister** [comment]
Yeah, I think I will roll out with an extension of the existing image. Should be fairly straightforward.

**Comment by kornicameister** [comment]
@timothyb89 to be honest, we could have an image to utilize topic creation without extending aforementioned image. We would have to write small Java/Scala App though. See this [question](https://stackoverflow.com/questions/16946778/how-can-we-create-a-topic-in-kafka-from-the-ide-using-api/23360100#23360100).

**Comment by timothyb89** [comment]
Huh, interesting find! I almost want to hack in support for that to pykafka... that would be a huge help in our python bits.

**Comment by kornicameister** [comment]
Hmm...yeah we could do that, but as long as there's no support from API it will take some time :/. 
I haven't seen any, have you ?

**Comment by kornicameister** [comment]
Wrong button :/

**Comment by timothyb89** [comment]
So, to be clear I think the "simple" way forward (for now at least) is to call out to create-topics.sh like everyone recommends, though  That being said..

I read through the code for AdminUtils from the example you linked, it looks like it just makes a bunch of calls out to ZooKeeper. I'd bet it could be replicated in python with kazoo pretty easily... may have to look into that at some point :smile:

**Comment by kornicameister** [comment]
@timothyb89 ok, so for now I will roll with extending the base image and the Python approach we'll leave for later. Once I submit the PR with kafka-init, or prior to, I guess I'll create an issue to keep that future extension in mind.
