### ISSUE TITLE
Default organization of admin is "Main Org."

### ISSUE THREAD

**Issue by knakazono** [monasca/monasca-docker#188]
When logging into grafana as "admin" user, the default organization is set "Main Org.".
![admin_organization](https://user-images.githubusercontent.com/18343425/29914576-ff6adf7a-8e73-11e7-954c-2788abc5a5d2.JPG)

Because of it, "admin" user cannot set data source with keystone auth.
The default organization should be "admin".
And "Main Org." doesn't exist in keystone, so I think it should not be registered here.

**Comment by knakazono** [comment]
@matrixik @kornicameister @timothyb89 @haruki-yamanashi

**Comment by knakazono** [comment]
@witekest

**Comment by matrixik** [comment]
Looks like it's not possible to change it only for admin on Grafana start-up, probably will need to use Grafana REST API to change it in `grafana-init` container.

**Comment by matrixik** [comment]
When investigating #374 I found that by default Grafana and keystone have user with name `admin` and then user from Keystone overwrite user from Grafana. Grafana user then loss admin privileges.

**Comment by matrixik** [comment]
Default Grafana admin user name was changed to `grafana-admin` in https://github.com/monasca/monasca-docker/commit/40ba63ead3d65bf8f3057f7ad15b3abe09b0b848 so it no more clash with Keystone admin.
