### ISSUE TITLE
monasca/kibana docker image is not updated

### ISSUE THREAD

**Issue by knakazono** [monasca/monasca-docker#190]
Hi,

I heard the docker images which are related with this project are updated automatically when merging patches.
However, monasca/kibana image seems not to be updated.
https://hub.docker.com/r/monasca/kibana/
The last update date of the image is 10 days ago, but the last patch below was merged 7 days ago.
https://github.com/monasca/monasca-docker/commit/3083183f592c48fa84ca4c181c733ed29d8914cd

Does anyone know why the docker image is not updated now?

**Comment by knakazono** [comment]
@matrixik @kornicameister @timothyb89 @haruki-yamanashi

**Comment by knakazono** [comment]
@witekest

**Comment by witekest** [comment]
@timothyb89 @mhoppal Could you please elaborate on how pushing the images from the CI works? I can see in [handle_push function](https://github.com/monasca/monasca-docker/blob/master/ci.py#L461) but don't understand how it is controlled and when the images are pushed.

**Comment by timothyb89** [comment]
It does work pretty strangely, that's on the short list for improvements once I have bandwidth to work on this more. Right now images are only automatically pushed if `build.yml` is changed which works fine when version numbers in `build.yml` relate directly to the container itself, as all of our custom containers here do (like keystone-init, etc).

For images that use external versions (from OpenStack) or automatic tagging (datestamps) you have to manually request an image to be pushed using `!push`. For security reasons it only checks the final merge commit (to make sure a project member approves the release), meaning you need to write `!push <component name>` on its own line in the box immediately after clicking the green 'Merge' button.

If a `!push` is forgotten, make a PR with an empty commit and go through the usual process, e.g.
```
git checkout -b rebuild-kibana
git commit --allow-empty -m "Rebuild kibana"
git push fork rebuild-kibana
hub pull-request
```

Then approve the (empty) PR and add a new line with `!push kibana` into the merge commit message box.

Eventually we'd like to integrate a bit with GitHub's API and use a "push" label for this instead, and probably give some feedback via automatic comments as well. Soon™

**Comment by knakazono** [comment]
Thanks for your great help.
I created a new pull request for updating images.
https://github.com/monasca/monasca-docker/pull/197

If I'm misunderstanding your comment, please let me know.

**Comment by knakazono** [comment]
Thanks! I confirmed the images in dockerhub has been updated by the above patch.

**Comment by matrixik** [comment]
Maybe we should add this info to all build.yml files?
