### ISSUE TITLE
Add restart policies on Kafka, Zookeeper and monasca-persister

### ISSUE THREAD

**Issue by nseyvet** [monasca/monasca-docker#237]
Hi,

As per title, it improves stability of the overall deployment.

**Comment by nseyvet** [comment]
See pull request https://github.com/monasca/monasca-docker/pull/238

**Comment by kornicameister** [comment]
Fixed in #238

**Comment by kornicameister** [comment]
@nseyvet please use ```Closes #{issue_number}``` in PRs next time, that way the issue will be closed automatically ;-)

**Comment by nseyvet** [comment]
Yes. Sorry for that.
