### ISSUE TITLE
Containers without build.yml file

### ISSUE THREAD

**Issue by matrixik** [monasca/monasca-docker#285]
Looks like there is no `build.yml` file in the following folders:
* https://github.com/monasca/monasca-docker/tree/master/monasca-forwarder
  But it has tags from 5 months ago: https://hub.docker.com/r/monasca/forwarder/tags/
* https://github.com/monasca/monasca-docker/tree/master/monasca-perf
* https://github.com/monasca/monasca-docker/tree/master/spark

**Comment by timothyb89** [comment]
Hmm, I think we can probably just remove those directories for now, they'll still be in the history if we ever need them again (which I somewhat doubt). I'll put up a PR to do so shortly.
