### ISSUE TITLE
Too many warnings/errors in start up phase

### ISSUE THREAD

**Issue by Brandstetter** [monasca/monasca-docker#305]
During start up (~first 50 seconds) of metric- and log pipeline ~6000 lines of logs will be created.
grep for "error" --> ~70 lines
grep for "warning" --> ~140 lines

**Comment by kornicameister** [comment]
That's because components try to connect to each other (couple times). Until succeed there's going to be a lot of errors.

**Comment by Brandstetter** [comment]
well, such cases should be just a warning, shouldn't it?

**Comment by kornicameister** [comment]
These are mostly the exceptions etc. It is generally a bad practice to hide them.
Not to mention that this is expected behaviour, so I kind of can't see the error that you see.
