### ISSUE TITLE
[fix] Monasca Log API health-check in Dockerfile

### ISSUE THREAD

**Issue by chersicm** [monasca/monasca-docker#365]
The Dockerfile invokes health-check.sh with wrong parameters.

In fact, in the Dockerfile you have:

HEALTHCHECK --interval=10s --timeout=5s \
  CMD /health-check.sh \
    $KEYSTONE_AUTH_URI \
    $KEYSTONE_ADMIN_USER \
    $KEYSTONE_ADMIN_PASSWORD \
    $KEYSTONE_ADMIN_TENANT \
    $KEYSTONE_ADMIN_DOMAIN \
    $MONASCA_CONTAINER_LOG_API_PORT

But health-check.sh takes only 1 parameter, so you should have:

HEALTHCHECK --interval=10s --timeout=5s \
  CMD /health-check.sh \
    $MONASCA_CONTAINER_LOG_API_PORT

**Comment by chersicm** [comment]
This solution works, at least to have the correct values assigned.

#!/bin/sh

# Default values for executing it manually on the host
curl --include --silent --show-error --output - \
    http://localhost:${MONASCA_CONTAINER_LOG_API_PORT:-5607}/healthcheck 2>&1 | \
    awk '
        BEGIN {status_code="0"; body=""; output=""}
        $1 ~ /^HTTP\// {status_line=$0; status_code=$2}
        $1 ~ /^\{/ {body=$0}
        {output=output $0 "\n"}
        END {
            if(status_code=="200") {
                print status_line;
                print body;
            } else {
                print output;
                exit 2;
            }
        }'

exit $?

**Comment by matrixik** [comment]
Thank you, that was probably copy/paste error because of monasca-api-python: https://github.com/monasca/monasca-docker/blob/master/monasca-api-python/health-check.sh
