### ISSUE TITLE
the monasca app of grafana does not work 

### ISSUE THREAD

**Issue by willhope** [monasca/monasca-docker#403]
when i click the monasca app in grafana,  grafana raise the  error : "grafana Error: XHR error (404 Not Found)"。when i rebuid the monasca-grafana-app in container,  and copy /var/lib/grafana/plugins/monasca-grafana-app/dist/* to /var/lib/grafana/plugins/monasca-grafana-app/, then it work! is it bug?

**Comment by matrixik** [comment]
Thank you for report, looking into this.

**Comment by matrixik** [comment]
Looks like problem is with not merged  #402 
Will merge when tests pass.

**Comment by matrixik** [comment]
It's merged now, test again, please.
If it's not working reopen this bug.

**Comment by willhope** [comment]
thanks, it works. but it still has some problems, when i flush the overview panel, raise this error : "Failed to get alarm counts. Object.entries is not a function"

**Comment by matrixik** [comment]
You could raise errors you find in https://github.com/monasca/monasca-grafana
