### ISSUE TITLE
Build monasca image for grafana

### ISSUE THREAD

**Issue by mehuljn** [monasca/monasca-docker#459]
There has been an update to include the feature of mapping alerts to notification in Grafana Monasca UI (app).

Is there a way I can rebuild the monasca image for grafana?
Or else if any one can build it for me.

Thanks

**Comment by timothyb89** [comment]
I've just posted https://github.com/monasca/monasca-docker/pull/460 to update the version, it should automatically publish a new image once merged.

In the mean time you should be able to test locally by building the container with the build arg `MONASCA_APP_REPO` set to `https://github.com/monasca/monasca-grafana.git`.

**Comment by maestropandy** [comment]
@timothyb89 as you mentioned to build container locally, changed docker file as below


> version: '3'
> services:
> 
>   grafana:
>     image: monasca/grafana:4.0.0-1.4.2
>     build:
>       context: .
>       args:
>         MONASCA_APP_REPO: https://github.com/monasca/monasca-grafana.git
>         MONASCA_APP_BRANCH: master
>     environment:
>       GF_AUTH_BASIC_ENABLED: "false"
>       GF_USERS_ALLOW_SIGN_UP: "false"
>       GF_USERS_ALLOW_ORG_CREATE: "false"
>       GF_AUTH_KEYSTONE_ENABLED: "true"
>       GF_AUTH_KEYSTONE_AUTH_URL: http://192.168.56.151:5000
>       GF_AUTH_KEYSTONE_VERIFY_SSL_CERT: "false"
>       GF_AUTH_KEYSTONE_DEFAULT_DOMAIN: "Default"
>       LOGSTASH_FIELDS: "service=grafana"
>     ports:
>       - "3000:3000"
>     depends_on:
>       - monasca
> 
>   grafana-init:
>     image: monasca/grafana-init:1.3.0
>     environment:
>       GRAFANA_USERNAME: monasca
>       GRAFANA_PASSWORD: jio@1234
>       DATASOURCE_TYPE: monasca
>       DATASOURCE_URL: http://monasca:8070/
>       DATASOURCE_ACCESS_MODE: proxy
>       DATASOURCE_AUTH: Keystone
>       LOGSTASH_FIELDS: "service=grafana-init"
>     depends_on:
>       - grafana
> 
> 

After built container "docker stack deploy -c grafana.yml grafana" being deploying in docker swarm, but the changes not reflected. 

Do need to build new image ?

**Comment by matrixik** [comment]
@timothyb89 I created PR https://github.com/monasca/grafana/pull/3 that should fix this problem with building Grafana image that you encounter in #460.

**Comment by matrixik** [comment]
To build new `grafana` image locally:
1. Go to folder `monasca-docker/grafana`
2. Run command `docker build --no-cache -t monasca/grafana:<new_version> .`
    where `<new_version>` is some new version you want, then replace this number in `docker-compose.yml` or in your `grafana.yml` file.

Closing.
