### ISSUE TITLE
Not able to attach notification to Alarm Definitions under Grafana Dashboard

### ISSUE THREAD

**Issue by maestropandy** [monasca/monasca-docker#465]
Hi, 

Using latest monasca/grafana image "monasca/grafana:4.0.0-1.5.0" as per the latest commit to this image, it should support "attach notification to alarm definition" but its not happening. 

Has anyone checked it by adding "Notification_ID or Notification Name" to "alarm_action" under grafana_dasboard alarm definition page. 

It was working fine with CLI, but not with grafana dashboard

Reference: [459](https://github.com/monasca/monasca-docker/issues/459)

**Comment by dougszumski** [comment]
Are you sure you don't just need to rebuild the container? The patch for allowing you to add notifications to alarms was only merged recently. The dockerfile references the master branch of the Monasca Grafana App, so it should pick it up the fix automatically during image build.

**Comment by matrixik** [comment]
@dougszumski  It's already rebuild https://hub.docker.com/r/monasca/grafana/tags/
It's not automatic we rebuilt it by hand in #460 
I think he is right that there is something wrong with adding notification (when I was looking into it adding webhook notification to alarm definition was possible after second or third try, and clicking box to add it did not showed list of all notification - they started appearing after I put some letter into box, forgot to fill issue).

**Comment by dougszumski** [comment]
@matrixik I think Charana intended it to work as auto-complete, rather than a list. It doesn't sound right that it took two or three tries to get it to work. If you check the Grafana logs were there any Monasca API call failures? Please file a bug in the plugin if you think there's an issue. We have Charana until Friday.

**Comment by maestropandy** [comment]
> @dougszumski It's already rebuild https://hub.docker.com/r/monasca/grafana/tags/
> It's not automatic we rebuilt it by hand in #460
> I think he is right that there is something wrong with adding notification (when I was looking into it adding webhook notification to alarm definition was possible after second or third try, and clicking box to add it did not showed list of all notification - they started appearing after I put some letter into box, forgot to fill issue).

@dougszumski "grafana docker logs having message "[Note]: Getting error while reading "mon-api" database using "mon' user" other than that there is no log related to listing notifications.

Mostly after creating new alarm_definitions, update it with one time  "notification name" 

Note: "notification name" drop down is not available, need to give details manually. 

Also "matchby" parameter need value to be passed will be great to avoid alarm mapping to all hostnames

Example: Create alarm-definitions by mapping to "tenant-name" or "VM_name" instead of matching by "hostname", "device", "component"

**Comment by dougszumski** [comment]
@maestropandy Please can file these issues (one issue per github issue) in the related repository here: https://github.com/monasca/monasca-grafana/issues

**Comment by maestropandy** [comment]
@dougszumski done https://github.com/monasca/monasca-grafana/issues/19

**Comment by matrixik** [comment]
Issue created in monasca-grafana. Closing.
