### ISSUE TITLE
agent-collector &  agent-forwarder   

### ISSUE THREAD

**Issue by mellitiseifeddine** [monasca/monasca-docker#470]
i have 3 VMs and i already deployed monasca component using docker on one of the VMs ,i having an issue where to deploy the agent-collector and forwarder  .
thx

**Comment by timothyb89** [comment]
At least in our example `docker-compose.yml` the agent is only configured to monitor the host it's currently running on. If you wanted to collect host metrics from multiple VMs you'd need to run a copy of the agent on each host.

The agent-collector and agent-forwarder are a pair that should always be deployed together. In [Kubernetes](https://github.com/monasca/monasca-helm) we deploy a pod containing both the collector and forwarder to each host in the cluster automatically.
