### ISSUE TITLE
Monasca-monitoring not working

### ISSUE THREAD

**Issue by zhangjianweibj** [monasca/monasca-docker#474]
hello, as the document describe ，added mysql environment tag,but agent pods no mysql.yml file in /etc/monasca/conf.d .why?

![image](https://user-images.githubusercontent.com/18585129/48999607-1daa0100-f192-11e8-89b4-402c21a30a8a.png)

env as follows:
![image](https://user-images.githubusercontent.com/18585129/48999459-b2f8c580-f191-11e8-9546-2313d54041e6.png)

and agent pods env 
![image](https://user-images.githubusercontent.com/18585129/48999556-f6533400-f191-11e8-9f81-79a8beb5fde1.png)

very thanks.

**Comment by matrixik** [comment]
Hello, 
Could you provide some more information for example how did you run agent-collector container? What command and if you restarted it after changing configuration? Templating all configuration files happen at the container start.
I can't reproduce it locally. When I run default containers with default configuration in this repository I have all proper files:
```
/etc/monasca/agent/conf.d # ls
cadvisor_host.yaml   cpu.yaml             disk.yaml            http_check.yaml      kafka_consumer.yaml  load.yaml            memory.yaml          mysql.yaml           process.yaml         zk.yaml
```

**Comment by matrixik** [comment]
Also looks like you are using quite old version of this container. The newest one is `master-20180914-130916`.

You can check last tested versions in:
https://github.com/monasca/monasca-docker/blob/master/.env

**Comment by zhangjianweibj** [comment]
@matrixik very thanks.i install agent by kubernetes deployment.yaml file as follows.
![image](https://user-images.githubusercontent.com/18585129/49050836-3f51c980-f220-11e8-9147-1c480318cee2.png)
![image](https://user-images.githubusercontent.com/18585129/49050850-52fd3000-f220-11e8-90cb-97119faaef9a.png)
![image](https://user-images.githubusercontent.com/18585129/49050860-5abcd480-f220-11e8-873d-143e4739da6a.png)
![image](https://user-images.githubusercontent.com/18585129/49050866-64463c80-f220-11e8-9ad4-d29e0e899363.png)
![image](https://user-images.githubusercontent.com/18585129/49050875-6c05e100-f220-11e8-82fb-316732a5a688.png)
![image](https://user-images.githubusercontent.com/18585129/49050886-72945880-f220-11e8-8773-db56c7343bb9.png)

**Comment by zhangjianweibj** [comment]
and agent version is monasca/agent-collector:master-20180112-162543.agent confid.d directory has prometheus.yml kubernetes.yml but no mysql.yml.

**Comment by matrixik** [comment]
You need to use monasca/agent-collector container in newer version.

**Comment by zhangjianweibj** [comment]
@matrixik ok,very thanks.
