### ISSUE TITLE
monasca docker install error

### ISSUE THREAD

**Issue by zhangjianweibj** [monasca/monasca-docker#481]
hello,i install monasca as document describe:docker-compose -f log-pipeline.yml -f docker-compose.yml up  ,but thresh and monasca-statsd components not working.erros as follws.

![image](https://user-images.githubusercontent.com/18585129/50151515-1642c700-02fc-11e9-8305-4626ec28410d.png)

![image](https://user-images.githubusercontent.com/18585129/50151532-235fb600-02fc-11e9-8cd1-b4b5006ebc19.png)

thresh component use storm as the document describe.

![image](https://user-images.githubusercontent.com/18585129/50151579-468a6580-02fc-11e9-8117-8c8d99d146da.png)

**Comment by matrixik** [comment]
Do you have `monasca-statsd` running?
https://github.com/monasca/monasca-docker/tree/master/monasca-statsd
https://github.com/monasca/monasca-docker/blob/master/docker-compose.yml#L214-L220

With the second problem I'm unable to help you. I never replaced thresh with storm in such way.

**Comment by zhangjianweibj** [comment]
thanks,i want to deploy Monasca on different nodes.and ensure each Monasca components are high available.but docker compse deploy monaca on same node.so i use docker swarm to deploy monasca with cmd "docker stack deploy -c docker-compose.yml".but encounter many errors.can your give me some advise?very thanks.

**Comment by matrixik** [comment]
Sorry, never worked with Docker Swarm, can't help you much.

**Comment by zhangjianweibj** [comment]
thanks.
