### ISSUE TITLE
aggregator lack of log level config property

### ISSUE THREAD

**Issue by zhangjianweibj** [monasca/monasca-docker#485]
aggregator can config log level in the config.yaml,but monasca-docker project lack of this property.this property should be available to users.
![image](https://user-images.githubusercontent.com/18585129/50418506-ad60cf00-0866-11e9-958e-17c219d1ae46.png)

![image](https://user-images.githubusercontent.com/18585129/50418514-bce01800-0866-11e9-96d3-bf3b263351a0.png)

**Comment by matrixik** [comment]
Thank you for report and fix.
