### ISSUE TITLE
Switch to multi-stage builds

### ISSUE THREAD

**Issue by timothyb89** [monasca/monasca-docker#80]
Docker now supports multi-stage builds: https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds

These would be a much better alternative to our `ARG` trickery.

**Comment by kornicameister** [comment]
I already done something similar [here](https://github.com/kornicameister/monasca-docker/blob/28245c870bee549e75af6a3ca25ac04058630d6d/kibana/Dockerfile#L1)

**Comment by kornicameister** [comment]
@timothyb89 in order to make it happen in CI, I think you'd need to update docker there. In #121 I am trying to submit kibana image that is using multi-stage feature, but seems like ```from``` keyword for ```COPY``` operation is unknown.

**Comment by timothyb89** [comment]
Ah, good point, I'll look into updating docker in Travis

**Comment by timothyb89** [comment]
For reference later, Travis has a document for upgrading... https://docs.travis-ci.com/user/docker/#Installing-a-newer-Docker-version
